#!/bin/env python3
"""
simply create a new file in the src and include folders
"""


import sys
from pathlib import Path

LICENSE_TXT = '''/*
LinearML - A Linear Algebra and Machine Learning "Library" in C
Copyright (c) 2023 Adwaith Rajesh <adwaithrajesh3180[at]gmail[dot]com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
'''

SRC_DIR = './src'
INCLUDE_DIR = './include'


def create_files(filepath: str) -> tuple[str, str]:
    '''
    returns the path to the files created
    '''

    src_path = (Path(SRC_DIR) / Path(filepath + '.c')).absolute()
    inc_path = (Path(INCLUDE_DIR) / Path(filepath + '.h')).absolute()

    # create the dirs if it does not exists
    src_path.parent.mkdir(exist_ok=True, parents=True)
    inc_path.parent.mkdir(exist_ok=True, parents=True)

    # crate the files
    src_path.touch(exist_ok=True)
    inc_path.touch(exist_ok=True)

    return str(src_path), str(inc_path)


def write_license_to_h(h_file_path: str) -> None:
    with open(h_file_path, 'w') as f:
        f.write(LICENSE_TXT)


def main() -> int:
    filename = sys.argv[1]
    _, header_file = create_files(filename)
    write_license_to_h(header_file)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
